version: '3.9'

services:
  db:
    image: postgres:14
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: globant_challenge
      POSTGRES_DB: headcount
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "6024:5432"

  api:
    build: .
    container_name: fastapi_container
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  pgdata: